/*
 * Copyright (c) 2020. The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *    IRT SystemX (https://www.kathra.org/)
 *
 */

/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.23.0-03
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kathra.nexus.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * BlobStoreQuotaResultXO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-01T16:18:10.112Z")
public class BlobStoreQuotaResultXO {
  @SerializedName("isViolation")
  private Boolean isViolation = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("blobStoreName")
  private String blobStoreName = null;

  public BlobStoreQuotaResultXO isViolation(Boolean isViolation) {
    this.isViolation = isViolation;
    return this;
  }

   /**
   * Get isViolation
   * @return isViolation
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsViolation() {
    return isViolation;
  }

  public void setIsViolation(Boolean isViolation) {
    this.isViolation = isViolation;
  }

  public BlobStoreQuotaResultXO message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public BlobStoreQuotaResultXO blobStoreName(String blobStoreName) {
    this.blobStoreName = blobStoreName;
    return this;
  }

   /**
   * Get blobStoreName
   * @return blobStoreName
  **/
  @ApiModelProperty(value = "")
  public String getBlobStoreName() {
    return blobStoreName;
  }

  public void setBlobStoreName(String blobStoreName) {
    this.blobStoreName = blobStoreName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlobStoreQuotaResultXO blobStoreQuotaResultXO = (BlobStoreQuotaResultXO) o;
    return Objects.equals(this.isViolation, blobStoreQuotaResultXO.isViolation) &&
        Objects.equals(this.message, blobStoreQuotaResultXO.message) &&
        Objects.equals(this.blobStoreName, blobStoreQuotaResultXO.blobStoreName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isViolation, message, blobStoreName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlobStoreQuotaResultXO {\n");
    
    sb.append("    isViolation: ").append(toIndentedString(isViolation)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    blobStoreName: ").append(toIndentedString(blobStoreName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

