/*
 * Copyright (c) 2020. The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *    IRT SystemX (https://www.kathra.org/)
 *
 */

/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.23.0-03
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kathra.nexus.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

/**
 * GroupAttributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-01T16:18:10.112Z")
public class GroupAttributes {
  @SerializedName("memberNames")
  private List<Object> memberNames = null;

  public GroupAttributes memberNames(List<Object> memberNames) {
    this.memberNames = memberNames;
    return this;
  }

  public GroupAttributes addMemberNamesItem(Object memberNamesItem) {
    if (this.memberNames == null) {
      this.memberNames = new ArrayList<Object>();
    }
    this.memberNames.add(memberNamesItem);
    return this;
  }

   /**
   * Member repositories&#39; names
   * @return memberNames
  **/
  @ApiModelProperty(example = "\"maven-public\"", value = "Member repositories' names")
  public List<Object> getMemberNames() {
    return memberNames;
  }

  public void setMemberNames(List<Object> memberNames) {
    this.memberNames = memberNames;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupAttributes groupAttributes = (GroupAttributes) o;
    return Objects.equals(this.memberNames, groupAttributes.memberNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(memberNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupAttributes {\n");
    
    sb.append("    memberNames: ").append(toIndentedString(memberNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

