/*
 * Copyright (c) 2020. The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *    IRT SystemX (https://www.kathra.org/)
 *
 */

/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.23.0-03
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kathra.nexus.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * HttpClientAttributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-01T16:18:10.112Z")
public class HttpClientAttributes {
  @SerializedName("blocked")
  private Boolean blocked = null;

  @SerializedName("autoBlock")
  private Boolean autoBlock = null;

  @SerializedName("connection")
  private HttpClientConnectionAttributes connection = null;

  @SerializedName("authentication")
  private HttpClientConnectionAuthenticationAttributes authentication = null;

  public HttpClientAttributes blocked(Boolean blocked) {
    this.blocked = blocked;
    return this;
  }

   /**
   * Whether to block outbound connections on the repository
   * @return blocked
  **/
  @ApiModelProperty(example = "false", required = true, value = "Whether to block outbound connections on the repository")
  public Boolean isBlocked() {
    return blocked;
  }

  public void setBlocked(Boolean blocked) {
    this.blocked = blocked;
  }

  public HttpClientAttributes autoBlock(Boolean autoBlock) {
    this.autoBlock = autoBlock;
    return this;
  }

   /**
   * Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive
   * @return autoBlock
  **/
  @ApiModelProperty(example = "false", required = true, value = "Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive")
  public Boolean isAutoBlock() {
    return autoBlock;
  }

  public void setAutoBlock(Boolean autoBlock) {
    this.autoBlock = autoBlock;
  }

  public HttpClientAttributes connection(HttpClientConnectionAttributes connection) {
    this.connection = connection;
    return this;
  }

   /**
   * Get connection
   * @return connection
  **/
  @ApiModelProperty(value = "")
  public HttpClientConnectionAttributes getConnection() {
    return connection;
  }

  public void setConnection(HttpClientConnectionAttributes connection) {
    this.connection = connection;
  }

  public HttpClientAttributes authentication(HttpClientConnectionAuthenticationAttributes authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * Get authentication
   * @return authentication
  **/
  @ApiModelProperty(value = "")
  public HttpClientConnectionAuthenticationAttributes getAuthentication() {
    return authentication;
  }

  public void setAuthentication(HttpClientConnectionAuthenticationAttributes authentication) {
    this.authentication = authentication;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HttpClientAttributes httpClientAttributes = (HttpClientAttributes) o;
    return Objects.equals(this.blocked, httpClientAttributes.blocked) &&
        Objects.equals(this.autoBlock, httpClientAttributes.autoBlock) &&
        Objects.equals(this.connection, httpClientAttributes.connection) &&
        Objects.equals(this.authentication, httpClientAttributes.authentication);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blocked, autoBlock, connection, authentication);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HttpClientAttributes {\n");
    
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    autoBlock: ").append(toIndentedString(autoBlock)).append("\n");
    sb.append("    connection: ").append(toIndentedString(connection)).append("\n");
    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

