/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.23.0-03
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kathra.nexus.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.kathra.nexus.client.model.AssetXO;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PageAssetXO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-26T20:07:05.892Z")
public class PageAssetXO {
  @SerializedName("items")
  private List<AssetXO> items = null;

  @SerializedName("continuationToken")
  private String continuationToken = null;

  public PageAssetXO items(List<AssetXO> items) {
    this.items = items;
    return this;
  }

  public PageAssetXO addItemsItem(AssetXO itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<AssetXO>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(value = "")
  public List<AssetXO> getItems() {
    return items;
  }

  public void setItems(List<AssetXO> items) {
    this.items = items;
  }

  public PageAssetXO continuationToken(String continuationToken) {
    this.continuationToken = continuationToken;
    return this;
  }

   /**
   * Get continuationToken
   * @return continuationToken
  **/
  @ApiModelProperty(value = "")
  public String getContinuationToken() {
    return continuationToken;
  }

  public void setContinuationToken(String continuationToken) {
    this.continuationToken = continuationToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageAssetXO pageAssetXO = (PageAssetXO) o;
    return Objects.equals(this.items, pageAssetXO.items) &&
        Objects.equals(this.continuationToken, pageAssetXO.continuationToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, continuationToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageAssetXO {\n");
    
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    continuationToken: ").append(toIndentedString(continuationToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

