/*
 * Copyright (c) 2020. The Kathra Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributors:
 *    IRT SystemX (https://www.kathra.org/)
 *
 */

/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.23.0-03
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kathra.nexus.client.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * ReadOnlyState
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-01T16:18:10.112Z")
public class ReadOnlyState {
  @SerializedName("systemInitiated")
  private Boolean systemInitiated = null;

  @SerializedName("summaryReason")
  private String summaryReason = null;

  @SerializedName("frozen")
  private Boolean frozen = null;

  public ReadOnlyState systemInitiated(Boolean systemInitiated) {
    this.systemInitiated = systemInitiated;
    return this;
  }

   /**
   * Get systemInitiated
   * @return systemInitiated
  **/
  @ApiModelProperty(value = "")
  public Boolean isSystemInitiated() {
    return systemInitiated;
  }

  public void setSystemInitiated(Boolean systemInitiated) {
    this.systemInitiated = systemInitiated;
  }

  public ReadOnlyState summaryReason(String summaryReason) {
    this.summaryReason = summaryReason;
    return this;
  }

   /**
   * Get summaryReason
   * @return summaryReason
  **/
  @ApiModelProperty(value = "")
  public String getSummaryReason() {
    return summaryReason;
  }

  public void setSummaryReason(String summaryReason) {
    this.summaryReason = summaryReason;
  }

  public ReadOnlyState frozen(Boolean frozen) {
    this.frozen = frozen;
    return this;
  }

   /**
   * Get frozen
   * @return frozen
  **/
  @ApiModelProperty(value = "")
  public Boolean isFrozen() {
    return frozen;
  }

  public void setFrozen(Boolean frozen) {
    this.frozen = frozen;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadOnlyState readOnlyState = (ReadOnlyState) o;
    return Objects.equals(this.systemInitiated, readOnlyState.systemInitiated) &&
        Objects.equals(this.summaryReason, readOnlyState.summaryReason) &&
        Objects.equals(this.frozen, readOnlyState.frozen);
  }

  @Override
  public int hashCode() {
    return Objects.hash(systemInitiated, summaryReason, frozen);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadOnlyState {\n");
    
    sb.append("    systemInitiated: ").append(toIndentedString(systemInitiated)).append("\n");
    sb.append("    summaryReason: ").append(toIndentedString(summaryReason)).append("\n");
    sb.append("    frozen: ").append(toIndentedString(frozen)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

